# common_core docs default
default: true

MD013: # line length
  line_length: 100
  code_blocks: false
  headings: false
  tables: false

MD024:
  siblings_only: true

MD033: false   # allow inline HTML (occasionally useful for code samples)
MD041: false   # no need to force first header in small docs
